spring:
  thymeleaf:
    mode: LEGACYHTML5
  profiles:
    active: dev
  mvc:
    favicon:
      enabled: false
  social:
    wechat:
    #   appid: your-app-id
    #   appsecret: your-app-secret
    #   mp:
    #     appid: your-app-id
    #     appsecret: your-app-secret
---

spring:
  profiles: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:nineteen;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    platform: h2
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show_sql: true
    format_sql: true
  h2:
    console:
      enabled: true
      path: /console
      settings:
        trace: false
        web-allow-others: false

server:
  session:
    timeout: 600
    cookie:
      http-only: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
  error:
    path: /e
logging:
  level:
    org.springframework.social: DEBUG
---

spring:
  profiles: qa
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost/nineteen?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    platform: mysql
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true

---

spring:
  profiles: prod
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://rm-wz94tjcas45h60u50.mysql.rds.aliyuncs.com/nineteen?useUnicode=true&characterEncoding=UTF-8
    username: nineteen
    password: shzyhxjzg@24
    platform: mysql
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show_sql: true
server:
  session:
    timeout: 900
    cookie:
      http-only: true
  tomcat:
    protocol-header: X-Forwarded-Proto
    remote-ip-header: X-Forwarded-For
  error:
    path: /e
# Disable mail server health checking to avoid too many connections to smtp server opened
management:
  health:
    mail:
      enabled: false
endpoints:
  enabled: false
  health.enabled: true
